os: linux

language: python
python: "3.8"

services:
  - docker


install:
  - cp .env.sample .env

stages:
  - name: build
    if: branch = master
  - name: build_tag
    if: (tag IS present) AND (branch = master)

jobs:
  include:
    - stage: build
      env: TAG=latest
      script: bash .travis/docker_build

    - stage: build_tag
      env: TAG=$TRAVIS_TAG
      script: bash .travis/docker_build