# Pyrogram
[pyrogram]
session_store="BABrUaeUyFGuCuKGsNkthNIeH5M-xXcjWwasntVVFKpup-bPQ6p8iDZDh3yFxhI0tfzG6B3Lk0fdG0lnaU7gS1cpZaz0w8NFnFwL9Mph128B-0vsfgYNaweOdlOfWi22muzJCIcuV-K7k4cSjakjmxnyW3cW5XwPWMjUIufR3bEtSffzoWNC5nAW5bgZhKH1DNtriXLJMQENuQvqm-wvCABwwNh4YIo_5ZO4UqVapHnrlwNSikOaF10RN32VjaFTK3dfHyEHyJIXzVDS4gAtpnG_Xr47eYYn5hECKwjGWX1M62UB2qH1THVaQfrZi-3wLW6Eo3W2EPugZaqFK_Qa2yT_B-v6MgA"
api_id=57125
api_hash="52433025d0a3806f5b9240994389827f"

[font]
# Font
font="shabnam.ttf"
