name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: personal-bot
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build docker.nix
    - run: nix-shell --run "echo OK"
