name: "Build"
on:
  pull_request:
  push:
jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: dearrude/personal-bot
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: personal-bot
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: $(nix-build docker.nix) | docker load
    - run: docker tag personal-bot docker.io/${{ steps.meta.outputs.tags }}
    - run: docker push -a dearrude/personal-bot
